// <auto-generated />
namespace ConfidentialEternalPottery.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Initdatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initdatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201410180003066_Init database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
